image:
  repository: docker.io/priyajith/samp-app-frontend
  tag: "0.1.0"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: frontend-staging.localtest.me
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

backendServiceName: backend-staging-backend
backendServicePort: 8080
