apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://us.icr.io/helm-charts
    chart: frontend
    targetRevision: 0.1.0
    helm:
      valueFiles: [values.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions: ["CreateNamespace=true"]
