image:
  repository: docker.io/priyajith/samp-app-frontend
  tag: "0.1.0"
replicaCount: 3

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: frontend.localtest.me
      paths:
        - path: /
          pathType: Prefix
  tls: []

backendServiceName: backend
backendServicePort: 8080
