apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/priyajithc/sample-system.git
    targetRevision: main
    path: charts/backend
    helm:
      valueFiles: [values.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: ["CreateNamespace=true"]
